### ISSUE TITLE
Error while opening ntds.dit file

### ISSUE THREAD

**Issue by c0d3xpl0it** [yosqueoy/ditsnap#1]
Hello

I dumped the ntds.dit file from the AD (manually, using other tools) and try to open the file using the ditsnap.exe, I faced below error. Can you guide on same (Screenshot attached) ?
http://pasteboard.co/ccDQghwP6.png

**Comment by yosqueoy** [comment]
Your ntds.dit file needs to be repaired by the following command because it's dirty shutdown state.
`esentutil /repair `
See below for the detail.
https://technet.microsoft.com/en-us/library/hh875504(v=ws.11).aspx
